apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  namespace: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test-service
  namespace: webapp
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 32000  # Ensure this port is not in use
  selector:
    app: nginx-test
